version: '3.8'

services:
  postgres:
    build: .
    image: postgres:15-alpine
    container_name: olist_postgres
    environment:
      POSTGRES_USER: olist_user
      POSTGRES_PASSWORD: olist_password
      POSTGRES_DB: olist_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/sql
      - ./data:/data
    restart: unless-stopped

volumes:
  postgres_data:
